# Configuration file for MegaLinter
DISABLE_LINTERS:
  - REPOSITORY_CHECKOV
  - REPOSITORY_KICS
  - REPOSITORY_TRIVY
  - SPELL_LYCHEE

JSON_ESLINT_PLUGIN_JSONC_FILTER_REGEX_EXCLUDE: "renovate.json$"
YAML_V8R_FILTER_REGEX_EXCLUDE: "renovate.json$|.mega-linter.yaml$"
