apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-
spec:
  serviceAccountName: argo
  entrypoint: main
  templates:
    - name: main
      container:
        image: docker/whalesay
        command: ["cowsay"]
