apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    app: minio
spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: main
          image: minio/minio
          env:
            - name: MINIO_ACCESS_KEY
              value: admin
            - name: MINIO_SECRET_KEY
              value: password
          ports:
            - containerPort: 9000
              name: api
            - containerPort: 9001
              name: dashboard
          command: [minio, server, --console-address, ":9001", /data]
          lifecycle:
            postStart:
              exec:
                command: [mkdir, -p, /data/my-bucket]
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: minio
spec:
  selector:
    app: minio
  ports:
    - port: 9000
      name: api
      protocol: TCP
      targetPort: 9000
    - port: 9001
      name: dashboard
      protocol: TCP
      targetPort: 9001
---
apiVersion: v1
stringData:
  accesskey: admin
  secretkey: password
kind: Secret
metadata:
  name: my-minio-cred
  labels:
    app: minio
type: Opaque
