kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argo-events-wf-create
  namespace: argo-events
rules:
- apiGroups: ["argoproj.io"]
  resources: ["workflows"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-events-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-events-wf-create
  namespace: argo-events
subjects:
- kind: ServiceAccount
  name: default
  namespace: argo-events
